#!/bin/bash

server=localhost:4200
room=1596b8c1-cb87-4542-be6b-9dbb1ad952a1
board=bb0507e3-e6a4-40e5-98f9-a4febecc2725

# how many pointers
pointers=4

# runtime in sec
length=120

for i in $(seq 1 ${pointers}); do
  node pointer.js -n -r 10 -s $server -b $board -m $room -t $length -e 10 &
  sleep 0.1
done

wait
