// @ts-ignore
import { JSONSchemaMarkdown } from 'json-schema-md-doc';

export class SAGE3Doc extends JSONSchemaMarkdown {
  footer = '';
  constructor() {
    super();
    this.footer = 'Generated by SAGE3';
  }
  load(schema: any) {
    super.load(schema);
  }
  generate() {
    return super.generate();
  }
  writePath(level: number, path: string) {
    // super.writePath(level, path);
  }
  writeAdditionalItems(bool: boolean, level: number) {
    if (super.notEmpty(bool)) {
      if (bool) {
        // this.writeLine('This schema <u>does not</u> accept additional items.', level);
      } else {
        super.writeLine('This schema accepts additional items.', level);
      }
    }
  }
  writeAdditionalProperties(bool: boolean, level: number) {
    if (super.notEmpty(bool)) {
      if (!bool) {
        // this.writeLine("This schema <u>does not</u> accept additional properties.", level);
      } else {
        super.writeLine('This schema accepts additional properties.', level);
      }
    }
  }
}
