import React, { useEffect, useRef, useState } from 'react';
import { useColorMode } from '@chakra-ui/react';
import { App } from '../../../schema';
// EChart imports
import * as echarts from 'echarts';
import { processStations } from '../utils';

const EChartsViewer = (): JSX.Element => {
  const [chartStateInstance, setChartStateInstance] = useState<echarts.ECharts | null>(null);
  const { colorMode } = useColorMode();

  const chartRef = useRef<any>(null);

  useEffect(() => {
    if (chartStateInstance) {
      echarts.dispose(chartStateInstance);
    }
    if (!chartRef.current) return;
    let chartInstance: echarts.ECharts | null = null;

    const renderInstance = echarts.getInstanceByDom(chartRef.current);
    if (renderInstance) {
      chartInstance = renderInstance;
    } else {
      chartInstance = echarts.init(chartRef.current, colorMode);
    }
    chartInstance.resize({
      height: 300,
      width: 300,
    });
    const awaitProcessStations = async () => {
      const chartOptions: echarts.EChartsCoreOption[] = await processStations({
        '0506': {
          attributes: ['RF_1_Tot', 'Tair_1_Avg', 'SM_1_Avg'],
          transformations: ['none'],
          chartType: ['Scatter Chart'],
          available_attribute_info: {
            available_variable_names: [
              'Incoming shortwave radiation',
              'Outgoing shortwave radiation',
              'Incoming longwave radiation',
              'Outgoing longwave radiation',
              'Net shortwave radiation',
              'Net longwave radiation',
              'Net incoming radiation',
              'Net outgoing radiation',
              'Net radiation',
              'Albedo',
              'Surface temperature',
              'Sky temperature',
              'Air temperature sensor 1',
              'Air temperature sensor 2',
              'Relative humidity sensor 1',
              'Relative humidity sensor 2',
              'Vapor pressure sensor 1',
              'Vapor pressure sensor 2',
              'Saturation vapor pressure sensor 1',
              'Saturation vapor pressure sensor 2',
              'Vapor pressure deficit sensor 1',
              'Vapor pressure deficit sensor 2',
              'Mean wind speed',
              'Resultant vector wind speed',
              'Unit vector average wind direction',
              'Resultant vector wind direction',
              'Wind direction standard deviation wind speed weighted',
              'Wind direction standard deviation',
              'Pressure',
              'Sea level pressure',
              'Tsoil_Avg',
              'Soil heat flux sensor 1',
              'Surface soil heat flux',
              'Soil moisture sensor 1',
              'Soil moisture sensor 2',
              'Soil moisture sensor 3',
              'Rainfall',
              'Minimum air temperature sensor 1',
              'Maximum air temperature sensor 1',
              'Minimum air temperature sensor 2',
              'Maximum air temperature sensor 2',
              'Minimum relative humidity sensor 1',
              'Maximum relative humidity sensor 1',
              'Minimum relative humidity sensor 1',
              'Maximum relative humidity sensor 1',
              'Minimum soil temperature',
              'Maximum soil temperature',
              'Maximum wind speed',
              'Battery voltage',
              'Logger panel temperature',
              'Enclosure relative humidity',
              '5-minute cellular data usage',
              'Cellular signal strength',
              'Cellular signal quality',
              'NR01 sensor body temperature',
              'NR01 heater duty cycle',
              'Wind_GoodSample_Avg',
              'Minutely rainfall',
              'Date',
            ],
            available_variable_ids: [
              'SWin_1_Avg',
              'SWout_1_Avg',
              'LWin_1_Avg',
              'LWout_1_Avg',
              'SWnet_1_Avg',
              'LWnet_1_Avg',
              'Rin_1_Avg',
              'Rout_1_Avg',
              'Rnet_1_Avg',
              'Albedo_1_Avg',
              'Tsrf_1_Avg',
              'Tsky_1_Avg',
              'Tair_1_Avg',
              'Tair_2_Avg',
              'RH_1_Avg',
              'RH_2_Avg',
              'VP_1_Avg',
              'VP_2_Avg',
              'VPsat_1_Avg',
              'VPsat_2_Avg',
              'VPD_1_Avg',
              'VPD_2_Avg',
              'WS_1_Avg',
              'WSrs_1_Avg',
              'WDuv_1_Avg',
              'WDrs_1_Avg',
              'WD_1_StdY',
              'WD_1_StdCS',
              'P_1',
              'Psl_1',
              'Tsoil_Avg',
              'SHF_1_Avg',
              'SHFsrf_1_Avg',
              'SM_1_Avg',
              'SM_2_Avg',
              'SM_3_Avg',
              'RF_1_Tot',
              'Tair_1_Min',
              'Tair_1_Max',
              'Tair_2_Min',
              'Tair_2_Max',
              'RH_1_Min',
              'RH_1_Max',
              'RH_2_Min',
              'RH_2_Max',
              'Tsoil_1_Min',
              'Tsoil_1_Max',
              'WS_1_Max',
              'BattVolt',
              'Tpanel',
              'RHenc',
              'CellUsage5min',
              'CellStr',
              'CellQlt',
              'Trnet_Avg',
              'DutyCycle_Avg',
              'Wind_GoodSample_Avg',
              'RFmin_1',
              'Date',
            ],
          },
        },
        '0501': {
          attributes: ['RF_1_Tot', 'Tair_1_Avg', 'RH_1_Avg'],
          transformations: ['none'],
          chartType: ['Scatter Chart'],
          available_attribute_info: {
            available_variable_names: [
              'BV_dis_Avg',
              'SWup_Avg',
              'SWdn_Avg',
              'LWup_Avg',
              'LWdn_Avg',
              'NR01 sensor body temperature',
              'Air temperature sensor 1',
              'Relative humidity sensor 1',
              'Air temperature sensor 2',
              'Relative humidity sensor 2',
              'WindSpeed',
              'WindSpeed_rs',
              'WindDir',
              'WindDir_sd',
              'WindDir_uv',
              'Tsoil_Avg',
              'SoilHeatFlux_Avg(1)',
              'SoilHeatFlux_Avg(2)',
              'SoilMoisture_Avg(1)',
              'SoilMoisture_Avg(2)',
              'SoilMoisture_Avg(3)',
              'SM_us_Avg(1)',
              'SM_us_Avg(2)',
              'SM_us_Avg(3)',
              'SoilMoisture_T_Avg',
              'Rainfall_Tot',
              'Minutely rainfall',
              'Logger panel temperature',
              'Enclosure relative humidity',
              'NR01 heater duty cycle',
              'Minimum NR01 heater duty cycle',
              'Maximum NR01 heater duty cycle',
              'Logger lithium battery voltage',
              'Battery voltage',
              'Minimum battery voltage',
              'Maximum battery voltage',
              'Number of scans',
              'Incoming shortwave radiation',
              'Outgoing shortwave radiation',
              'Incoming longwave radiation',
              'Outgoing longwave radiation',
              'Net shortwave radiation',
              'Net longwave radiation',
              'Net incoming radiation',
              'Net outgoing radiation',
              'Net radiation',
              'Albedo',
              'Surface temperature',
              'Sky temperature',
              'Vapor pressure sensor 1',
              'Vapor pressure sensor 2',
              'Saturation vapor pressure sensor 1',
              'Saturation vapor pressure sensor 2',
              'Vapor pressure deficit sensor 1',
              'Vapor pressure deficit sensor 2',
              'Mean wind speed',
              'Resultant vector wind speed',
              'Wind direction standard deviation',
              'Unit vector average wind direction',
              'Wind direction standard deviation wind speed weighted',
              'Resultant vector wind direction',
              'Pressure',
              'Sea level pressure',
              'Tsoil_TCAV_Avg',
              'SHF_1_8cm_Avg',
              'SHF_2_8cm_Avg',
              'Surface soil heat flux',
              'SM_1_H4cm_Avg',
              'SM_2_V15cm_Avg',
              'SM_3_V45cm_Avg',
              'Rainfall',
              'Minimum air temperature sensor 1',
              'Maximum air temperature sensor 1',
              'Minimum air temperature sensor 2',
              'Maximum air temperature sensor 2',
              'Minimum relative humidity sensor 1',
              'Maximum relative humidity sensor 1',
              'Minimum relative humidity sensor 1',
              'Maximum relative humidity sensor 1',
              'Minimum soil temperature',
              'Maximum soil temperature',
              'Maximum wind speed',
              'Maximum wind gust',
              'Thermocouple temperature',
              'Soil temperature sensor 1',
              'Soil heat flux sensor 1',
              'Soil heat flux sensor 2',
              'Soil moisture sensor 1',
              'Soil moisture sensor 2',
              'Soil moisture sensor 3',
              'Soil temperature sensor 2',
              'Soil temperature sensor 3',
              'Soil temperature sensor 4',
              'Maximum rain intensity',
              '5-minute cellular data usage',
              'Cellular signal strength',
              'Cellular signal quality',
              'Rain gauge tip',
              'Date',
            ],
            available_variable_ids: [
              'BV_dis_Avg',
              'SWup_Avg',
              'SWdn_Avg',
              'LWup_Avg',
              'LWdn_Avg',
              'Trnet_Avg',
              'Tair_1_Avg',
              'RH_1_Avg',
              'Tair_2_Avg',
              'RH_2_Avg',
              'WindSpeed',
              'WindSpeed_rs',
              'WindDir',
              'WindDir_sd',
              'WindDir_uv',
              'Tsoil_Avg',
              'SoilHeatFlux_Avg(1)',
              'SoilHeatFlux_Avg(2)',
              'SoilMoisture_Avg(1)',
              'SoilMoisture_Avg(2)',
              'SoilMoisture_Avg(3)',
              'SM_us_Avg(1)',
              'SM_us_Avg(2)',
              'SM_us_Avg(3)',
              'SoilMoisture_T_Avg',
              'Rainfall_Tot',
              'RFmin_1',
              'Tpanel',
              'RHenc',
              'DutyCycle_Avg',
              'DutyCycle_Min',
              'DutyCycle_Max',
              'LGR_LiBattV',
              'BattVolt',
              'BattVolt_Min',
              'BattVolt_Max',
              'Nscans',
              'SWin_1_Avg',
              'SWout_1_Avg',
              'LWin_1_Avg',
              'LWout_1_Avg',
              'SWnet_1_Avg',
              'LWnet_1_Avg',
              'Rin_1_Avg',
              'Rout_1_Avg',
              'Rnet_1_Avg',
              'Albedo_1_Avg',
              'Tsrf_1_Avg',
              'Tsky_1_Avg',
              'VP_1_Avg',
              'VP_2_Avg',
              'VPsat_1_Avg',
              'VPsat_2_Avg',
              'VPD_1_Avg',
              'VPD_2_Avg',
              'WS_1_Avg',
              'WSrs_1_Avg',
              'WD_1_StdCS',
              'WDuv_1_Avg',
              'WD_1_StdY',
              'WDrs_1_Avg',
              'P_1',
              'Psl_1',
              'Tsoil_TCAV_Avg',
              'SHF_1_8cm_Avg',
              'SHF_2_8cm_Avg',
              'SHFsrf_1_Avg',
              'SM_1_H4cm_Avg',
              'SM_2_V15cm_Avg',
              'SM_3_V45cm_Avg',
              'RF_1_Tot',
              'Tair_1_Min',
              'Tair_1_Max',
              'Tair_2_Min',
              'Tair_2_Max',
              'RH_1_Min',
              'RH_1_Max',
              'RH_2_Min',
              'RH_2_Max',
              'Tsoil_1_Min',
              'Tsoil_1_Max',
              'WS_1_Max',
              'WG_1_Max',
              'TCair_Avg',
              'Tsoil_1_Avg',
              'SHF_1_Avg',
              'SHF_2_Avg',
              'SM_1_Avg',
              'SM_2_Avg',
              'SM_3_Avg',
              'Tsoil_2',
              'Tsoil_3',
              'Tsoil_4',
              'RFint_1_Max',
              'CellUsage5min',
              'CellStr',
              'CellQlt',
              'RGtip_1_Tot',
              'Date',
            ],
          },
        },
        '0431': {
          attributes: ['RF_1_Tot', 'Tsrf_1_Avg', 'RH_1_Avg'],
          transformations: ['none'],
          chartType: ['Scatter Chart'],
          available_attribute_info: {
            available_variable_names: [
              'Incoming shortwave radiation',
              'Outgoing shortwave radiation',
              'Incoming longwave radiation',
              'Outgoing longwave radiation',
              'Net shortwave radiation',
              'Net longwave radiation',
              'Net incoming radiation',
              'Net outgoing radiation',
              'Net radiation',
              'Albedo',
              'Surface temperature',
              'Sky temperature',
              'Air temperature sensor 1',
              'Air temperature sensor 2',
              'Relative humidity sensor 1',
              'Relative humidity sensor 2',
              'Vapor pressure sensor 1',
              'Vapor pressure sensor 2',
              'Saturation vapor pressure sensor 1',
              'Saturation vapor pressure sensor 2',
              'Vapor pressure deficit sensor 1',
              'Vapor pressure deficit sensor 2',
              'Mean wind speed',
              'Resultant vector wind speed',
              'Unit vector average wind direction',
              'Resultant vector wind direction',
              'Wind direction standard deviation wind speed weighted',
              'Wind direction standard deviation',
              'Pressure',
              'Sea level pressure',
              'Soil temperature sensor 1',
              'Soil heat flux sensor 1',
              'Surface soil heat flux',
              'Soil moisture sensor 1',
              'Soil moisture sensor 2',
              'Soil moisture sensor 3',
              'Soil temperature sensor 2',
              'Soil temperature sensor 3',
              'Soil temperature sensor 4',
              'Rainfall',
              'Maximum rain intensity',
              'Minimum air temperature sensor 1',
              'Maximum air temperature sensor 1',
              'Minimum air temperature sensor 2',
              'Maximum air temperature sensor 2',
              'Minimum relative humidity sensor 1',
              'Maximum relative humidity sensor 1',
              'Minimum relative humidity sensor 1',
              'Maximum relative humidity sensor 1',
              'Minimum soil temperature',
              'Maximum soil temperature',
              'Maximum wind gust',
              'Maximum wind speed',
              'Minutely rainfall',
              'Minutely rain gauge tips',
              'Battery voltage',
              'Logger panel temperature',
              'Enclosure relative humidity',
              '5-minute cellular data usage',
              'Cellular signal strength',
              'Cellular signal quality',
              'NR01 sensor body temperature',
              'NR01 heater duty cycle',
              'Rain gauge tip',
              'Date',
            ],
            available_variable_ids: [
              'SWin_1_Avg',
              'SWout_1_Avg',
              'LWin_1_Avg',
              'LWout_1_Avg',
              'SWnet_1_Avg',
              'LWnet_1_Avg',
              'Rin_1_Avg',
              'Rout_1_Avg',
              'Rnet_1_Avg',
              'Albedo_1_Avg',
              'Tsrf_1_Avg',
              'Tsky_1_Avg',
              'Tair_1_Avg',
              'Tair_2_Avg',
              'RH_1_Avg',
              'RH_2_Avg',
              'VP_1_Avg',
              'VP_2_Avg',
              'VPsat_1_Avg',
              'VPsat_2_Avg',
              'VPD_1_Avg',
              'VPD_2_Avg',
              'WS_1_Avg',
              'WSrs_1_Avg',
              'WDuv_1_Avg',
              'WDrs_1_Avg',
              'WD_1_StdY',
              'WD_1_StdCS',
              'P_1',
              'Psl_1',
              'Tsoil_1_Avg',
              'SHF_1_Avg',
              'SHFsrf_1_Avg',
              'SM_1_Avg',
              'SM_2_Avg',
              'SM_3_Avg',
              'Tsoil_2',
              'Tsoil_3',
              'Tsoil_4',
              'RF_1_Tot',
              'RFint_1_Max',
              'Tair_1_Min',
              'Tair_1_Max',
              'Tair_2_Min',
              'Tair_2_Max',
              'RH_1_Min',
              'RH_1_Max',
              'RH_2_Min',
              'RH_2_Max',
              'Tsoil_1_Min',
              'Tsoil_1_Max',
              'WG_1_Max',
              'WS_1_Max',
              'RFmin_1',
              'RGtipmin_1',
              'BattVolt',
              'Tpanel',
              'RHenc',
              'CellUsage5min',
              'CellStr',
              'CellQlt',
              'Trnet_Avg',
              'DutyCycle_Avg',
              'RGtip_1_Tot',
              'Date',
            ],
          },
        },
      });
      console.log(chartOptions);
      if (chartInstance) chartInstance.setOption(chartOptions[0]);
    };
    awaitProcessStations();

    // Set the chart options
    setChartStateInstance(chartInstance);
  }, [chartRef, colorMode]);

  return (
    <>
      <div ref={chartRef} style={{ backgroundColor: 'white' }}></div>
    </>
  );
};

export default EChartsViewer;
