/**
 * Copyright (c) SAGE3 Development Team 2022. All Rights Reserved
 * University of Hawaii, University of Illinois Chicago, Virginia Tech
 *
 * Distributed under the terms of the SAGE3 License.  The full license is in
 * the file LICENSE, distributed as part of this software.
 */

export const traindata = [
  { query: 'chart average nominal over time', VisualizationTask: 'trend' },
  { query: 'scatterplot nominal vs nominal per nominal', VisualizationTask: 'correlation' },
  { query: 'How does the nominal of from different countries vary by the number of nominal?', VisualizationTask: 'correlation' },
  { query: 'chart number of vehicles by nominal in buckets of 500', VisualizationTask: 'distribution' },
  {
    query: 'show a stacked bar chart of number of vehicles to number for nominal grouped by nominal',
    VisualizationTask: 'distribution',
  },
  { query: 'chart average nominal to nominal', VisualizationTask: 'value' },
  { query: 'chart count to nominal', VisualizationTask: 'distribution' },
  { query: 'scatterplot nominal vs nominal', VisualizationTask: 'correlation' },
  { query: 'scatterplot nominal vs nominal separated by nominal', VisualizationTask: 'correlation' },
  { query: 'How does nominal vary by nominal for from different nominals?', VisualizationTask: 'correlation' },
  { query: 'What is the average nominal for  with different nominal?', VisualizationTask: 'value' },
  { query: 'How does nominal vary by the number of nominal in a car?', VisualizationTask: 'correlation' },
  { query: 'Distribution of nominal', VisualizationTask: 'distribution' },
  { query: 'Histogram of nominal', VisualizationTask: 'distribution' },
  { query: 'Scatterplot of nominal by nominal colored by nominal', VisualizationTask: 'correlation' },
  { query: 'A scatterplot of nominal on X axis and Acceleration on Y axis', VisualizationTask: 'correlation' },
  { query: 'Histogram with nominal on X axis and bar colored by nominal', VisualizationTask: 'distribution' },
  { query: 'Distribution of nominal', VisualizationTask: 'distribution' },
  { query: 'Average nominal by nominal and nominal of nominal in separate panels', VisualizationTask: 'correlation' },
  { query: 'Average nominal by nominal histogram', VisualizationTask: 'correlation' },
  { query: 'How does nominal change with nominal?', VisualizationTask: 'correlation' },
  { query: 'How does nominal behave compared to nominal?', VisualizationTask: 'distribution' },
  { query: 'How many are from each nominal?', VisualizationTask: 'correlation' },
  { query: 'how does nominal compare to nominal', VisualizationTask: ' correlation' },
  { query: 'For each nominal', VisualizationTask: ' correlation' },
  { query: 'How has nominal changed over time in each nominal?', VisualizationTask: 'line' },
  { query: 'what is the breakdown of nominals by the number of nominal in each nominal?', VisualizationTask: 'distribution' },
  { query: 'How many nominals have various numbers of nominal in each nominal?', VisualizationTask: 'distribution' },
  { query: 'What is the average nominal of nominal by nominal nominal?', VisualizationTask: 'value' },
  { query: 'How has the average nominal of nominal changed over the temporal?', VisualizationTask: 'trend' },
  { query: 'which nominals of the us should we prioritize for directing resources', VisualizationTask: 'extremum' },
  { query: 'chart of quantitative versus temporal colored by nominal', VisualizationTask: 'trend' },
  { query: 'would you be able to pull up a nominal chart with temporal colored by nominal', VisualizationTask: ' ' },
  { query: 'would you be able to pull up a chart of nominal that are not available or nominal', VisualizationTask: 'extremum' },
  { query: 'would you be able to pull up a chart of nominal that are not available or nominal', VisualizationTask: 'extremum' },
  { query: 'can we see a chart of poverty by the nominal', VisualizationTask: 'extremum' },
  { query: 'then maybe we can pull up the nominal chart as well', VisualizationTask: 'extremum' },
  { query: 'we can look at nominal also', VisualizationTask: 'anomoly' },
  { query: 'we can look at the diabetes after', VisualizationTask: ' anomoly' },
  { query: 'can you pull up a plot of nominal', VisualizationTask: 'anomoly' },
  { query: 'can you also pull up a plot for diabetes', VisualizationTask: 'anomoly' },
  { query: "quantitative for x's elderly", VisualizationTask: 'distribution' },
  { query: 'can we see a graph of poverty versus quantitative', VisualizationTask: 'trend' },
  { query: 'can we see a graph of social vulnerability versus quantitative', VisualizationTask: 'trend' },
  { query: 'can you pull up a line chart for poverty versus nominals', VisualizationTask: 'trend' },
  {
    query: 'party can we get a map of nominal filtered by nominal and suburban and urban and nominal',
    VisualizationTask: 'correlation',
  },
  { query: 'can you pull up a line chart of nominal versus quantitative in nominal', VisualizationTask: 'trend' },
  { query: 'can you get a map of nominal filtered by small', VisualizationTask: 'distribution' },
  { query: 'can we get a line chart of quantitative filtered by nominal and nominal', VisualizationTask: 'trend' },
  { query: 'talk to you sunday can we see a histogram of nominal filtered by', VisualizationTask: 'distribution' },
  { query: 'histogram of nominal filtered by nominal', VisualizationTask: 'distribution' },
  { query: 'can we get a chart of nominal versus or filtered by midwest', VisualizationTask: 'anomoly' },
  { query: 'shows the map of a nominal in the pacific shows the pacific nominal', VisualizationTask: 'value' },
  { query: 'can you show us a map of the nominal for the non constituents', VisualizationTask: 'value' },
  { query: 'can you show us a visualization of nominal by nominal', VisualizationTask: 'anomoly' },
  { query: 'can you show us a chart of the diabetes rate', VisualizationTask: 'distribution' },
  { query: 'can we have a map of nominal filtered by nominal and nominal', VisualizationTask: 'ditribution' },
  { query: 'can we see a map of nominal filtered by nominal', VisualizationTask: 'correlation' },
  { query: 'can you show us a map of nominal filtered by nominal and nominal', VisualizationTask: 'correlation' },
  { query: 'can we see a map of nominal filtered by nominal and nominal', VisualizationTask: 'correlation' },
  { query: 'can you show us where the nominal and the nominal', VisualizationTask: 'distribution' },
  { query: 'correlation between nominal and the nominal', VisualizationTask: 'correlation' },
  { query: 'can we see where nominal nominal', VisualizationTask: 'distribution' },
  { query: 'can you show us a map of nominal who are nominal', VisualizationTask: 'correlation' },
  { query: 'can you show us a map of nominal filtered by nominal', VisualizationTask: 'correlation' },
  { query: 'can you show us a heat map of nominal and nominal', VisualizationTask: 'correlation' },
  { query: 'can you show us a heat map chart of hispanic and diabetes', VisualizationTask: 'correlation' },
  { query: 'can we see the map of quantitative', VisualizationTask: 'distribution' },
  { query: 'can we see a map of urban areas in the nominal with nominal', VisualizationTask: 'anomoly' },
  { query: 'can we have a map of nominal filtered by the nominal and small city in rural', VisualizationTask: 'anomoly' },
];
