#!/bin/bash

# URL
#server="traoumad.evl.uic.edu"
server="localhost:4200"

# runtime in sec
length=60

# which board
room="7c49fabf-74f2-40e1-88e4-5728f55770f0"
board="dedcf4b9-374e-4ceb-b47d-54026bca407d"

# how many pointers
pointers=10

for i in $(seq 1 ${pointers})
do
	node pointer.js -r 15 -s $server -b $board -m $room-m $room -t $length &
done


# Usage: pointer [options]
#
# Options:
# -V, --version      output the version number
# -b, --board <s>    board id (string)) (default: "board0")
# -t, --timeout <n>  runtime in sec (number) (default: 10)
# -r, --rate <n>     framerate (number) (default: 10)
# -s, --server <s>   Server URL (string) (default: "http://localhost:3333")
# -h, --help         display help for command

