#!/bin/bash

# URL
#server="https://traoumad.evl.uic.edu"
server="http://localhost:4200"

# runtime in sec
length=60

# which board
board="board0"

# how many pointers
pointers=10

for i in $(seq 1 ${pointers})
do
	node pointer.js -r 15 -s $server -b $board -t $length &
done


# Usage: pointer [options]
#
# Options:
# -V, --version      output the version number
# -b, --board <s>    board id (string)) (default: "board0")
# -t, --timeout <n>  runtime in sec (number) (default: 10)
# -r, --rate <n>     framerate (number) (default: 10)
# -s, --server <s>   Server URL (string) (default: "http://localhost:3333")
# -h, --help         display help for command

