#!/bin/bash

# Usage: pointer [options]
#
# Options:
# -V, --version      output the version number
# -b, --board <s>    board id (string)) (default: "board0")
# -t, --timeout <n>  runtime in sec (number) (default: 10)
# -r, --rate <n>     framerate (number) (default: 10)
# -s, --server <s>   Server URL (string) (default: "http://localhost:3333")
# -e, --sensitivity <n>  sensitivity (number) (default: 5)
# -h, --help         display help for command

# URL
#server="traoumad.evl.uic.edu"
server="127.0.0.1:3333"

# runtime in sec
length=120

# which board
room="c809cd21-32fe-4b94-a487-5582b69ab364"
board="29577580-b326-4aff-836c-d2f65250ee97"

# how many pointers
pointers=20

for i in $(seq 1 ${pointers}); do
  node pointer.js -r 20 -s $server -b $board -m $room -t $length -e 10 &
  sleep 0.1
done
