export const jsonSample = {
    "cell_type": "code",
    "execution_count": 69,
    "metadata": {},
    "outputs": [
    {
        "data": {
        "application/json": {
            "cell": {
            "!": "OSMagics",
            "HTML": "Other",
            "SVG": "Other",
            "bash": "Other",
            "capture": "ExecutionMagics",
            "debug": "ExecutionMagics",
            "file": "Other",
            "html": "DisplayMagics",
            "javascript": "DisplayMagics",
            "js": "DisplayMagics",
            "latex": "DisplayMagics",
            "perl": "Other",
            "prun": "ExecutionMagics",
            "pypy": "Other",
            "python": "Other",
            "python2": "Other",
            "python3": "Other",
            "ruby": "Other",
            "script": "ScriptMagics",
            "sh": "Other",
            "svg": "DisplayMagics",
            "sx": "OSMagics",
            "system": "OSMagics",
            "time": "ExecutionMagics",
            "timeit": "ExecutionMagics",
            "writefile": "OSMagics"
            },
            "line": {
            "aimport": "AutoreloadMagics",
            "alias": "OSMagics",
            "alias_magic": "BasicMagics",
            "autocall": "AutoMagics",
            "automagic": "AutoMagics",
            "autoreload": "AutoreloadMagics",
            "autosave": "KernelMagics",
            "bookmark": "OSMagics",
            "cat": "Other",
            "cd": "OSMagics",
            "clear": "KernelMagics",
            "colors": "BasicMagics",
            "config": "ConfigMagics",
            "connect_info": "KernelMagics",
            "cp": "Other",
            "debug": "ExecutionMagics",
            "dhist": "OSMagics",
            "dirs": "OSMagics",
            "doctest_mode": "BasicMagics",
            "ed": "Other",
            "edit": "KernelMagics",
            "env": "OSMagics",
            "gui": "BasicMagics",
            "hist": "Other",
            "history": "HistoryMagics",
            "killbgscripts": "ScriptMagics",
            "ldir": "Other",
            "less": "KernelMagics",
            "lf": "Other",
            "lk": "Other",
            "ll": "Other",
            "load": "CodeMagics",
            "load_ext": "ExtensionMagics",
            "loadpy": "CodeMagics",
            "logoff": "LoggingMagics",
            "logon": "LoggingMagics",
            "logstart": "LoggingMagics",
            "logstate": "LoggingMagics",
            "logstop": "LoggingMagics",
            "ls": "Other",
            "lsmagic": "BasicMagics",
            "lx": "Other",
            "macro": "ExecutionMagics",
            "magic": "BasicMagics",
            "man": "KernelMagics",
            "matplotlib": "PylabMagics",
            "mkdir": "Other",
            "more": "KernelMagics",
            "mv": "Other",
            "notebook": "BasicMagics",
            "page": "BasicMagics",
            "pastebin": "CodeMagics",
            "pdb": "ExecutionMagics",
            "pdef": "NamespaceMagics",
            "pdoc": "NamespaceMagics",
            "pfile": "NamespaceMagics",
            "pinfo": "NamespaceMagics",
            "pinfo2": "NamespaceMagics",
            "popd": "OSMagics",
            "pprint": "BasicMagics",
            "precision": "BasicMagics",
            "profile": "BasicMagics",
            "prun": "ExecutionMagics",
            "psearch": "NamespaceMagics",
            "psource": "NamespaceMagics",
            "pushd": "OSMagics",
            "pwd": "OSMagics",
            "pycat": "OSMagics",
            "pylab": "PylabMagics",
            "qtconsole": "KernelMagics",
            "quickref": "BasicMagics",
            "recall": "HistoryMagics",
            "rehashx": "OSMagics",
            "reload_ext": "ExtensionMagics",
            "rep": "Other",
            "rerun": "HistoryMagics",
            "reset": "NamespaceMagics",
            "reset_selective": "NamespaceMagics",
            "rm": "Other",
            "rmdir": "Other",
            "run": "ExecutionMagics",
            "save": "CodeMagics",
            "sc": "OSMagics",
            "set_env": "OSMagics",
            "store": "StoreMagics",
            "sx": "OSMagics",
            "system": "OSMagics",
            "tb": "ExecutionMagics",
            "time": "ExecutionMagics",
            "timeit": "ExecutionMagics",
            "unalias": "OSMagics",
            "unload_ext": "ExtensionMagics",
            "watermark": "WaterMark",
            "who": "NamespaceMagics",
            "who_ls": "NamespaceMagics",
            "whos": "NamespaceMagics",
            "xdel": "NamespaceMagics",
            "xmode": "BasicMagics"
            }
        },
        "text/plain": [
            "Available line magics:\n",
            "%aimport  %alias  %alias_magic  %autocall  %automagic  %autoreload  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %watermark  %who  %who_ls  %whos  %xdel  %xmode\n",
            "\n",
            "Available cell magics:\n",
            "%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile\n",
            "\n",
            "Automagic is ON, % prefix IS NOT needed for line magics."
        ]
        },
        "execution_count": 69,
        "metadata": {},
        "output_type": "execute_result"
    }
    ],
    "source": ["# You can even use these to run javascript, html etc in cells\n", "%lsmagic"]
}
