#!/bin/bash

#docker login ghcr.io

# macOS
if [[ $OSTYPE == 'darwin'* ]]; then

  #security -v unlock-keychain ~/Library/Keychains/login.keychain-db

  if [[ `uname -m` == 'arm64' ]]; then
    docker buildx build --push -f node_server/Dockerfile --platform linux/arm64 --tag ghcr.io/sage-3/next:dev_arm64 ..
    docker buildx build --push -f foresight/Dockerfile   --platform linux/arm64 --tag ghcr.io/sage-3/foresight:dev_arm64 ..
  fi

  # Intel
  if [[ `uname -m` == 'x86_64' ]]; then
    docker buildx build --push -f node_server/Dockerfile --platform linux/amd64 --tag ghcr.io/sage-3/next:dev_amd64 ..
    docker buildx build --push -f foresight/Dockerfile   --platform linux/amd64 --tag ghcr.io/sage-3/foresight:dev_amd64 ..
  fi

fi

# linux
if [[ $OSTYPE == 'linux'* ]]; then
  docker buildx build --push -f node_server/Dockerfile --platform linux/amd64 --tag ghcr.io/sage-3/next:dev_amd64 ..
  docker buildx build --push -f foresight/Dockerfile   --platform linux/amd64 --tag ghcr.io/sage-3/foresight:dev_amd64 ..
fi


