#!/bin/bash

# stage foresight inside the notebook folder
rm -fr configurations/jupyter/notebooks/foresight
cp -r ../foresight configurations/jupyter/notebooks/


# macOS
if [[ $OSTYPE == 'darwin'* ]]; then

  # M1
  if [[ `uname -m` == 'arm64' ]]; then
    docker buildx build -f node_server/Dockerfile.m1 --platform linux/arm64 --tag sage3/next:prod ..
    docker buildx build -f foresight/Dockerfile      --platform linux/arm64 --tag sage3/foresight ..
  fi

  # Intel
  if [[ `uname -m` == 'x86_64' ]]; then
    docker buildx build -f node_server/Dockerfile.prod --tag sage3/next:prod ..
    docker buildx build -f foresight/Dockerfile        --tag sage3/foresight ..
  fi

fi

# linux
if [[ $OSTYPE == 'linux'* ]]; then
  docker buildx build --push -f node_server/Dockerfile.prod --platform linux/amd64 --tag sage3/next:prod ..
  docker buildx build --push -f foresight/Dockerfile        --platform linux/amd64 --tag sage3/foresight ..
fi


