#!/bin/sh

docker-compose -f docker-compose-backend.yml stop
docker-compose -f docker-compose-backend.yml rm -f

docker rmi task-scheduler
docker rmi media-server
docker rmi `docker images -a --filter=dangling=true -q`

