services:
  redis-server:
    image: "redis/redis-stack-server:latest"
    volumes:
      - ./configurations/redis/data:/data
      - ./configurations/redis/conf:/conf
    ports:
      - "127.0.0.1:6379:6379"
    entrypoint: redis-server
    command: /conf/redis.conf
    deploy:
      restart_policy:
        condition: on-failure
  chromadb:
    image: "chromadb/chroma:0.5.16"
    ports:
      - "127.0.0.1:8100:8000"
    volumes:
      - ./configurations/chroma/data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic_authn.BasicAuthenticationServerProvider
      - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_SERVER_AUTHN_CREDENTIALS}
    command: "--workers 1 --proxy-headers --port 8000 --host 0.0.0.0 --timeout-keep-alive 30"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      restart_policy:
        condition: on-failure
  node-server:
    image: "ghcr.io/sage-3/next:arm64"
    ports:
      - "443:443"
    depends_on:
      - "redis-server"
      - "fluentd-server"
    volumes:
      - ./configurations/node/keys:/app/keys
      - ./configurations/node/assets:/app/dist/apps/homebase/assets
      - ./configurations/node/plugins:/app/dist/apps/homebase/plugins
      - ./configurations/node/sage3-prod.hjson:/app/sage3-prod.hjson
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${SAGE3_SERVER}"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  fluentd-server:
    image: "fluent/fluentd:edge-debian"
    ports:
      - "127.0.0.1:24224:24224"
    volumes:
      - ./configurations/fluentd/log:/fluentd/log
      - ./configurations/fluentd/conf:/fluentd/etc
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
  kernelserver:
    image: "ghcr.io/sage-3/sagekernelserver:arm64"
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - ENVIRONMENT=production
      - SAGE3_SERVER=${SAGE3_SERVER}
      - TOKEN=${TOKEN}
    restart: always
    working_dir: /app
    command: python src/main.py --url http://jupyter:8888
    depends_on:
      node-server:
        condition: service_healthy
      jupyter:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/heartbeat"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
  seer:
    image: "ghcr.io/sage-3/agents:arm64"
    ports:
      - "127.0.0.1:9999:9999"
    environment:
      - ENVIRONMENT=production
      - SAGE3_SERVER=${SAGE3_SERVER}
      - TOKEN=${TOKEN}
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic_authn.BasicAuthenticationServerProvider
      - CHROMA_CLIENT_AUTH_CREDENTIALS=${CHROMA_CLIENT_AUTH_CREDENTIALS}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      chromadb:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
  jupyter:
    image: "quay.io/jupyter/datascience-notebook:2024-05-27"
    volumes:
      - ./configurations/jupyter/conf:/conf
      - ./configurations/jupyter/notebooks:/home/jovyan/notebooks
      - ./redis-client:/home/jovyan/work
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - ENVIRONMENT=production
      - SAGE3_SERVER=${SAGE3_SERVER}
      - TOKEN=${TOKEN}
    depends_on:
      - "redis-server"
    command: /conf/start.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
