#!/bin/bash

# cleanup
rm -fr configurations/jupyter/notebooks/notebooks/.ipynb_checkpoints/
rm -fr configurations/jupyter/notebooks/ipynb/*.ipynb
rm -fr configurations/jupyter/notebooks/boards/.ipynb_checkpoints
rm -fr configurations/jupyter/notebooks/boards/*mipynb
rm -fr configurations/jupyter/notebooks/.ipynb_checkpoints
rm -f  configurations/redis/data/dump.rdb
cd configurations/node/assets && rm -f *.webp *.jpg *.json *.geojson *.pdf && cd -

# Pick a compose file
cp docker-compose-amd64.yml docker-compose.yml

VERSION=1.0-linux-amd64
rm -f SAGE3-${VERSION}.tgz

tar --exclude ".DS_Store" --exclude ".gitignore" --transform 's/^/SAGE3-1.0\//' -cvzf SAGE3-${VERSION}.tgz README.md configurations GO docker-compose.yml STOP

