#!/bin/bash

# cleanup
rm -fr configurations/jupyter/notebooks/notebooks/.ipynb_checkpoints/
rm -fr configurations/jupyter/notebooks/ipynb/*.ipynb
rm -fr configurations/jupyter/notebooks/boards/.ipynb_checkpoints
rm -fr configurations/jupyter/notebooks/boards/*mipynb
rm -fr configurations/jupyter/notebooks/.ipynb_checkpoints
rm -f configurations/redis/data/dump.rdb
cd configurations/node/assets && rm -f *.webp *.jpg *.json *.geojson *.pdf && cd -

# Pick a compose file
cp docker-compose-arm64.yml docker-compose.yml
cp .env.template .env

# Switch fluent to prod mode
cp configurations/fluentd/conf/fluent-prod.conf configurations/fluentd/conf/fluent.conf

VERSION=1.4-macos-arm64
rm -f SAGE3-${VERSION}.tgz

gtar --exclude ".DS_Store" --exclude ".gitignore" --transform 's/^/SAGE3-1.4\//' -cvzf SAGE3-${VERSION}.tgz README.md configurations GO docker-compose.yml STOP .env
