export type PaperNode = {
  id: string;
  label: string;
  is_cluster?: boolean;
  is_document?: boolean;
  level: number;
  children?: PaperNode[];
  title?: string;
  authors?: string[];
  year?: string;
  venue?: string;
  file_name?: string;
  keywords?: string[];
  summary?: string;
  research_questions?: string;
  methods?: string;
  findings?: string;
  field?: string;
  generated_label?: string;
};

export type Tree = {
  topic: string;
  size: number;
  children: Tree[];
  summary?: string;
  title?: string;
  authors?: string[];
  year?: string;
  venue?: string;
  url?: string;
  abstract?: string;
  tldr?: string;
  citations?: number;
  pdf_url?: string | null;
  source?: string;
};

/** Paper item from hierarchy.json (generated by AiSearch / DocuSageAzure pipeline) */
export type HierarchyPaper = {
  id: string;
  title: string;
  year: number;
  citations?: number;
  url?: string;
  authors?: string[];
  abstract?: string;
  venue?: string;
  pdf_url?: string | null;
  tldr?: string | null;
  source?: string;
};

/** Node from hierarchy.json (Phase 1, 2.7, 4, 6 pipeline output) */
export type HierarchyNode = {
  id: string;
  name: string;
  level: number;
  paper_count?: number;
  summary?: string;
  keywords?: string[];
  s2_fields?: string[];
  children?: HierarchyNode[];
  papers?: HierarchyPaper[];
};

/** Detect if JSON is hierarchy.json format (has id, name, and children or papers) */
export function isHierarchyFormat(json: unknown): json is HierarchyNode {
  if (!json || typeof json !== 'object') return false;
  const o = json as Record<string, unknown>;
  return (
    typeof o.id === 'string' &&
    typeof o.name === 'string' &&
    (Array.isArray(o.children) || Array.isArray(o.papers))
  );
}

/** Transform hierarchy.json (DocuSageAzure_reduced output) into Tree for DocuSAGE visualizations */
export function transformHierarchyToTree(node: HierarchyNode): Tree {
  if (node.children && node.children.length > 0) {
    return {
      topic: node.name,
      size: 0,
      children: node.children.map(transformHierarchyToTree),
      summary: node.summary,
    };
  }
  if (node.papers && node.papers.length > 0) {
    const paperChildren: Tree[] = node.papers.map((p) => ({
      topic: p.title,
      size: 1,
      children: [],
      title: p.title,
      year: p.year != null ? String(p.year) : undefined,
      venue: p.venue,
      url: p.url,
      abstract: p.abstract,
      tldr: p.tldr ?? undefined,
      citations: p.citations,
      pdf_url: p.pdf_url,
      source: p.source,
      authors: p.authors,
    }));
    return {
      topic: node.name,
      size: 0,
      children: paperChildren,
      summary: node.summary,
    };
  }
  return {
    topic: node.name,
    size: 0,
    children: [],
    summary: node.summary,
  };
}

// Function to transform the JSON data into the Tree structure
export function transformToTree(node: PaperNode): Tree {
  return {
    topic: node.label,
    size: node.is_document ? 1 : 0,
    children: node.children ? node.children.map(transformToTree) : [],
    summary: node.summary,
    title: node.title,
    authors: node.authors,
    year: node.year,
    venue: node.venue
  };
}

// Import the JSON data
import * as clusteringResults from './clustering_results.json';

// Transform the JSON data into the Tree structure
export const data: Tree = transformToTree(clusteringResults);
  