/**
 * Copyright (c) SAGE3 Development Team 2026. All Rights Reserved
 * University of Hawaii, University of Illinois Chicago, Virginia Tech
 *
 * Distributed under the terms of the SAGE3 License.  The full license is in
 * the file LICENSE, distributed as part of this software.
 */

// A user's own OpenAI-compatible credentials, kept in this browser only.
//
// These are deliberately NOT part of the `s3_user_settings` bundle: that blob
// is designed to be reset wholesale by "Restore Default Settings", and a key
// should never disappear as a side effect of resetting an unrelated preference.
// They are never sent to the SAGE3 server for storage — only attached to the
// AI requests that need them.

import { LLMCapability, LLMConfiguration } from '@sage3/shared/types';
import { USER_LLM_PROVIDER, UserLLMPayload } from '@sage3/shared';

/**
 * Storage.
 *
 * The record lives in `localStorage` so the key survives across sessions, which
 * is what a user pasting their own key expects. The API key inside it is
 * encrypted (AES-GCM) with a non-extractable key generated by this browser and
 * kept in IndexedDB. JavaScript can use that key but can never read it out, so:
 *   - anyone reading localStorage (DevTools, a copied profile, a backup) sees
 *     ciphertext, and copying IndexedDB alongside yields a key the browser
 *     refuses to export;
 *   - a script running on this origin can still decrypt while it runs here,
 *     which is why the key is also removed on logout (see useAuth) and never
 *     shown back on screen.
 * The model id and base URL are not secrets and stay readable synchronously,
 * so the UI and the provider list do not have to wait on a decryption.
 *
 * Where IndexedDB or WebCrypto is unavailable (strict private modes, some
 * kiosks) the credentials are held in memory for the session instead of being
 * written in clear.
 */
const backend = (): Storage | undefined => (typeof window === 'undefined' ? undefined : window.localStorage);
const STORAGE_KEY = 's3_user_llm';
const DB_NAME = 's3_user_llm_keys';
const DB_STORE = 'keys';
const DB_KEY_ID = 'aes-gcm';

export const USER_PROVIDER_NAME = USER_LLM_PROVIDER;

/** What the user's model is assumed to do: matches what the settings form offers */
export const USER_MODEL_CAPABILITIES: LLMCapability[] = ['chat', 'code', 'vision'];

export type UserLLMCredentials = {
  apiKey: string;
  baseUrl?: string;
  modelId: string;
};

/** The non-secret part of the credentials, readable without decrypting */
export type UserLLMInfo = Omit<UserLLMCredentials, 'apiKey'>;

// On-disk record. `enc` is base64(iv || AES-GCM ciphertext) of the API key.
type StoredRecord = { v: 2; modelId: string; baseUrl?: string; enc: string };
// Records written before encryption held the key in clear
type LegacyRecord = { apiKey?: string; modelId?: string; baseUrl?: string };

// Session-only fallback when the browser offers no IndexedDB or WebCrypto
let memoryCreds: UserLLMCredentials | undefined;

const cryptoAvailable = (): boolean => typeof window !== 'undefined' && typeof indexedDB !== 'undefined' && !!window.crypto?.subtle;

// ─── Browser-held encryption key ──────────────────────────────────────────────

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => req.result.createObjectStore(DB_STORE);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

function dbRequest<T>(mode: IDBTransactionMode, op: (store: IDBObjectStore) => IDBRequest<T>): Promise<T> {
  return openDb().then(
    (db) =>
      new Promise<T>((resolve, reject) => {
        const tx = db.transaction(DB_STORE, mode);
        const req = op(tx.objectStore(DB_STORE));
        req.onsuccess = () => resolve(req.result);
        req.onerror = () => reject(req.error);
        tx.oncomplete = () => db.close();
      }),
  );
}

async function getOrCreateKey(): Promise<CryptoKey> {
  const existing = await dbRequest<CryptoKey | undefined>('readonly', (s) => s.get(DB_KEY_ID));
  if (existing) return existing;
  // extractable: false is the whole point: the key can be used here, never exported
  const key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']);
  await dbRequest('readwrite', (s) => s.put(key, DB_KEY_ID));
  return key;
}

const toBase64 = (bytes: Uint8Array): string => btoa(String.fromCharCode(...bytes));
const fromBase64 = (b64: string): Uint8Array => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

async function encryptText(plain: string): Promise<string> {
  const key = await getOrCreateKey();
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, new TextEncoder().encode(plain)));
  const out = new Uint8Array(iv.length + cipher.length);
  out.set(iv);
  out.set(cipher, iv.length);
  return toBase64(out);
}

async function decryptText(b64: string): Promise<string | undefined> {
  try {
    const key = await dbRequest<CryptoKey | undefined>('readonly', (s) => s.get(DB_KEY_ID));
    if (!key) return undefined;
    const bytes = fromBase64(b64);
    const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: bytes.slice(0, 12) }, key, bytes.slice(12));
    return new TextDecoder().decode(plain);
  } catch (e) {
    // No key for this ciphertext (storage partially cleared or synced without
    // IndexedDB): the record is unusable and is treated as absent
    return undefined;
  }
}

// ─── Records ──────────────────────────────────────────────────────────────────

function readRecord(): StoredRecord | LegacyRecord | undefined {
  try {
    const raw = backend()?.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as StoredRecord | LegacyRecord) : undefined;
  } catch (e) {
    // Corrupt or unreadable storage (private mode, cleared data): behave as unset
    return undefined;
  }
}

const isEncrypted = (r: StoredRecord | LegacyRecord): r is StoredRecord => (r as StoredRecord).v === 2 && !!(r as StoredRecord).enc;

/**
 * The stored model id and base URL, without touching the key. Synchronous, so
 * the provider list and the settings form can show them at once. `undefined`
 * when no credentials are stored.
 */
export function getUserLLMInfo(): UserLLMInfo | undefined {
  if (memoryCreds) return { modelId: memoryCreds.modelId, baseUrl: memoryCreds.baseUrl };
  const r = readRecord();
  if (!r?.modelId) return undefined;
  if (!isEncrypted(r) && !r.apiKey) return undefined;
  return { modelId: r.modelId, baseUrl: r.baseUrl || undefined };
}

/** Are usable credentials stored? Synchronous; does not decrypt. */
export function hasUserLLM(): boolean {
  return getUserLLMInfo() !== undefined;
}

/**
 * The stored credentials with the key decrypted, or `undefined` when none are
 * stored or the key cannot be recovered. A record written before encryption
 * existed is re-saved encrypted on first read.
 */
export async function getUserLLM(): Promise<UserLLMCredentials | undefined> {
  if (memoryCreds) return memoryCreds;
  const r = readRecord();
  if (!r?.modelId) return undefined;
  if (isEncrypted(r)) {
    if (!cryptoAvailable()) return undefined;
    const apiKey = await decryptText(r.enc);
    if (!apiKey) {
      clearRecord();
      return undefined;
    }
    return { apiKey, modelId: r.modelId, baseUrl: r.baseUrl || undefined };
  }
  // Legacy clear-text record: migrate it
  if (!r.apiKey) return undefined;
  const creds: UserLLMCredentials = { apiKey: r.apiKey, modelId: r.modelId, baseUrl: r.baseUrl || undefined };
  try {
    await setUserLLM(creds);
  } catch (e) {
    // Could not re-save encrypted; still usable for this session
  }
  return creds;
}

/**
 * Store the credentials, encrypting the key. Throws when nothing can be
 * stored at all, so the caller can tell the user.
 */
export async function setUserLLM(creds: UserLLMCredentials): Promise<void> {
  const clean: UserLLMCredentials = {
    apiKey: creds.apiKey.trim(),
    baseUrl: creds.baseUrl?.trim().replace(/\/+$/, '') || undefined,
    modelId: creds.modelId.trim(),
  };
  if (!cryptoAvailable()) {
    // No way to encrypt: keep it for this session only rather than write it in clear
    memoryCreds = clean;
    clearRecord();
    return;
  }
  const record: StoredRecord = { v: 2, modelId: clean.modelId, baseUrl: clean.baseUrl, enc: await encryptText(clean.apiKey) };
  try {
    backend()?.setItem(STORAGE_KEY, JSON.stringify(record));
    memoryCreds = undefined;
  } catch (e) {
    // Storage unavailable or full — the caller reports failure to the user
    throw new Error('Could not save the key in this browser');
  }
}

function clearRecord(): void {
  try {
    backend()?.removeItem(STORAGE_KEY);
  } catch (e) {
    // Nothing to do: unreadable storage is already effectively cleared
  }
}

/** Remove the credentials and the browser-held key that encrypted them. */
export async function clearUserLLM(): Promise<void> {
  memoryCreds = undefined;
  clearRecord();
  if (!cryptoAvailable()) return;
  try {
    await dbRequest('readwrite', (s) => s.delete(DB_KEY_ID));
  } catch (e) {
    // Without the key the ciphertext is already unreadable; nothing more to do
  }
}

export function maskApiKey(apiKey: string): string {
  const tail = apiKey.slice(-4);
  return tail ? `••••••••${tail}` : '';
}

/**
 * Add the user's own credentials to an LLM configuration as an ordinary
 * provider, so everything that reasons about providers — capability gating,
 * the settings list, task availability — treats it like any other.
 *
 * Without this the user's provider is absent from the configuration, and
 * `canProviderPerformTask` returns false for *every* task, blocking even plain
 * chat. The key is deliberately left out: the manager never needs it, and
 * omitting it keeps the secret out of anything that serializes the config.
 *
 * Returns the configuration unchanged when no credentials are stored.
 */
export function withUserProvider(config: LLMConfiguration): LLMConfiguration {
  const creds = getUserLLMInfo();
  if (!config || !creds) return config;
  return {
    ...config,
    providers: {
      ...config.providers,
      [USER_PROVIDER_NAME]: {
        models: {
          [creds.modelId]: {
            model_id: creds.modelId,
            capabilities: USER_MODEL_CAPABILITIES,
          },
        },
      },
    },
  };
}

/**
 * The credentials in the shape the backend expects on the wire, or undefined
 * when none are stored. The base URL is normalized here so the backend receives
 * a value it can use directly.
 */
export async function userLLMPayload(): Promise<UserLLMPayload | undefined> {
  const creds = await getUserLLM();
  if (!creds) return undefined;
  return {
    apiKey: creds.apiKey,
    baseUrl: creds.baseUrl ? normalizeBaseUrl(creds.baseUrl) : undefined,
    modelId: creds.modelId,
  };
}

/** The endpoint used when no base URL is given. */
export const DEFAULT_BASE_URL = 'https://api.openai.com/v1';

/**
 * Normalize a base URL the way the backend does: strip trailing slashes and
 * append `/v1` when it is not already there, so a user can paste either
 * `https://host` or `https://host/v1` and get the same result.
 */
export function normalizeBaseUrl(url?: string): string {
  const trimmed = (url || '').trim().replace(/\/+$/, '');
  if (!trimmed) return DEFAULT_BASE_URL;
  if (trimmed.endsWith('/v1')) return trimmed;
  // Azure OpenAI's OpenAI-compatible surface lives under /openai/v1, not /v1:
  // https://<resource>.openai.azure.com/openai/v1. Accept the bare resource
  // host or the /openai prefix and complete it.
  if (isAzureOpenAI(trimmed)) return trimmed.endsWith('/openai') ? `${trimmed}/v1` : `${trimmed}/openai/v1`;
  return `${trimmed}/v1`;
}

/** Is this an Azure OpenAI resource endpoint (`*.openai.azure.com`)? */
export function isAzureOpenAI(url?: string): boolean {
  try {
    return new URL((url || '').trim()).hostname.toLowerCase().endsWith('.openai.azure.com');
  } catch {
    return false;
  }
}

/**
 * Ask an OpenAI-compatible endpoint which models it offers (`GET /models`).
 *
 * Returns the model ids, sorted. Throws with a readable message on failure —
 * callers should let an `AbortError` pass through untouched, since that means
 * the caller cancelled the request rather than the endpoint refusing it.
 *
 * @param apiKey the key to authenticate with
 * @param baseUrl optional base URL; defaults to OpenAI
 * @param signal abort signal, so an in-flight lookup can be cancelled
 */
export async function fetchAvailableModels(apiKey: string, baseUrl: string | undefined, signal: AbortSignal): Promise<string[]> {
  const url = `${normalizeBaseUrl(baseUrl)}/models`;
  const azure = isAzureOpenAI(baseUrl);
  let res: Response;
  try {
    // Azure accepts the key as a bearer token on its /openai/v1 surface but
    // documents the api-key header; send both so either configuration works
    const headers: Record<string, string> = { Authorization: `Bearer ${apiKey}` };
    if (azure) headers['api-key'] = apiKey;
    res = await fetch(url, { headers, signal });
  } catch (e) {
    // Let cancellation propagate so the caller can ignore it
    if (e instanceof DOMException && e.name === 'AbortError') throw e;
    // A network-level failure here is usually CORS, a bad host, or (for an
    // http:// endpoint) the page's own content-security policy
    throw new Error('Could not reach that endpoint: it is down, the address is wrong, or it does not allow requests from a browser');
  }
  if (res.status === 401 || res.status === 403) {
    throw new Error(azure ? 'Azure rejected that key' : 'That key was rejected');
  }
  if (res.status === 404) {
    throw new Error(`No /models at ${normalizeBaseUrl(baseUrl)}: check the base URL`);
  }
  if (!res.ok) {
    throw new Error(`Endpoint returned ${res.status}`);
  }
  const body = (await res.json()) as { data?: { id?: string }[] };
  const ids = (body?.data || []).map((m) => m?.id).filter((id): id is string => typeof id === 'string' && id.length > 0);
  if (ids.length === 0) throw new Error('No models returned');
  // Returned unfiltered: capable chat models are not reliably identifiable by
  // name (o-series, chatgpt-*, and every non-OpenAI endpoint's own naming), so
  // filtering would hide working models rather than only unusable ones
  return ids.sort((a, b) => a.localeCompare(b));
}
