/**
 * Copyright (c) SAGE3 Development Team 2023. All Rights Reserved
 * University of Hawaii, University of Illinois Chicago, Virginia Tech
 *
 * Distributed under the terms of the SAGE3 License.  The full license is in
 * the file LICENSE, distributed as part of this software.
 */

import { useEffect, useMemo, useState } from 'react';
import { Badge, Button, ButtonGroup, HStack, Select, Tooltip, useDisclosure, useToast } from '@chakra-ui/react';
import { MdAdd, MdArrowDropDown, MdFileDownload, MdHelp, MdRefresh, MdRemove } from 'react-icons/md';
// Date manipulation (for filename)
import dateFormat from 'date-fns/format';

import { downloadFile, useAppStore, useUser, useUsersStore, useBoardStore, useKernelStore } from '@sage3/frontend';
import { App } from '../../../schema';
import { state as AppState } from '../index';
import { HelpModal } from './help';
import { User } from '@sage3/shared/types';
import { KernelInfo } from '@sage3/shared/types';

/**
 * UI toolbar for the SAGEcell application
 *
 * @param {App} props
 * @returns {JSX.Element}
 */
export function ToolbarComponent(props: App): JSX.Element {
  // App State
  const s = props.data.state as AppState;
  const updateState = useAppStore((state) => state.updateState);

  // User state
  const { user } = useUser();
  const users = useUsersStore((state) => state.users);

  // Board Info
  const boardId = props.data.boardId;
  const boardName = useBoardStore((state) => state.boards).find((board) => board._id === boardId)?.data.name;

  // Local kernel info
  const [myKernels, setMyKernels] = useState<KernelInfo[]>([]);
  const [selected, setSelected] = useState<KernelInfo | undefined>(undefined);

  // Access
  const [access, setAccess] = useState<boolean>(true); // Default true, it will be updated later

  // Disclosure of Modal
  const { isOpen: helpIsOpen, onOpen: helpOnOpen, onClose: helpOnClose } = useDisclosure();

  // Kernel Store
  const { apiStatus, kernels, create, refreshKernels } = useKernelStore((state) => state);

  // Toast
  const toast = useToast();

  // Checking Acccess
  useEffect(() => {
    // If the API Status is down, set the publicKernels to empty array
    if (!apiStatus) {
      setAccess(false);
      return;
    } else if (kernels.length === 0 && apiStatus) {
      const selectedKernel = kernels.find((kernel) => kernel.kernel_id === s.kernel);
      const isPrivate = selectedKernel?.is_private;
      const owner = selectedKernel?.owner;
      if (!isPrivate) setAccess(true);
      else if (isPrivate && owner === user?._id) setAccess(true);
      else setAccess(false);
    }
  }, [apiStatus, kernels, s.kernel, user]);

  // Set Selected Kernel
  useEffect(() => {
    if (kernels.length === 0) return;
    else {
      const selectedKernel = kernels.find((kernel) => kernel.kernel_id === s.kernel);
      setSelected(selectedKernel);
    }
  }, [kernels, s.kernel]);

  // Set My Kernels
  useEffect(() => {
    if (kernels.length === 0) return;
    else {
      filterAndSetMyKernels(kernels);
    }
  }, [kernels]);

  // Filter out this board's kernels and boards this user has access to
  const filterAndSetMyKernels = (kernels: KernelInfo[]) => {
    const filteredKernels = kernels.filter((kernel) => kernel.board === props.data.boardId && hasKernelAccess(kernel));
    setMyKernels(filteredKernels);
  };

  /**
   * Check if the user has access to the kernel
   * @param {KernelInfo} kernel
   * @returns {boolean}
   * @memberof SageCell
   */
  const hasKernelAccess = (kernel: KernelInfo): boolean => {
    return !kernel.is_private || (kernel.is_private && kernel.owner === user?._id);
  };

  // Badge icon
  const [badgeText, badgeColorScheme] = useMemo(() => {
    if (apiStatus) {
      if (s.kernel && selected) {
        const owner = users.find((u: User) => u._id === selected.owner);
        if (selected.is_private) {
          return [selected.owner === user?._id ? 'Locked' : `Locked by ${owner?.data.name}`, 'red'];
        }
        return [`Ready`, 'green'];
      }
      return ['No Available Kernels', 'yellow'];
    }
    return ['Offline', 'red'];
  }, [apiStatus, selected, user?._id]);

  /**
   *
   * Add a kernel to the list of kernels by sending a request to the backend
   * and updating the state. Defaults to python3 kernel. Expects a kernel alias
   * and a kernel name.
   *
   * @returns  void
   */
  const createDefaultKernel = async () => {
    if (!user || apiStatus) return;
    const defaultAlias = boardName ? boardName.replace(/[^a-zA-Z0-9\-_]/g, '') : 'default';
    const kernelInfo = {
      kernel_id: '', // will be generated by the backend
      room: props.data.roomId,
      board: props.data.boardId,
      name: 'python3',
      alias: defaultAlias,
      is_private: false,
      owner: user._id,
    };
    const success = await create(kernelInfo);
    toast({
      title: success ? 'Kernel Created' : 'Kernel Creation Failed',
      description: success ? 'Kernel created successfully' : 'Kernel creation failed',
      status: success ? 'success' : 'error',
      duration: 3000,
      isClosable: true,
    });
  };

  /**
   * This is called when the user selects a kernel from the dropdown
   * It updates the global state and the app description
   * @param {React.ChangeEvent<HTMLSelectElement>} e
   * @returns {void}
   */
  function selectKernel(e: React.ChangeEvent<HTMLSelectElement>): void {
    const newKernelValue = e.target.value;
    console.log(newKernelValue);
    updateState(props._id, { kernel: newKernelValue });
  }

  /**
   * Download the stickie as a text file
   * @returns {void}
   */
  const downloadPy = (): void => {
    // Current date
    const dt = dateFormat(new Date(), 'yyyy-MM-dd-HH:mm:ss');
    // Get the text of the note
    const content = `${s.code}`;
    // generate a URL containing the text of the note
    const txturl = 'data:text/plain;charset=utf-8,' + encodeURIComponent(content);
    // Make a filename with username and date
    const filename = 'sagecell-' + dt + '.py';
    // Go for download
    downloadFile(txturl, filename);
  };

  // Increase font size
  const increaseFontSize = () => {
    updateState(props._id, { fontSize: Math.min(48, s.fontSize + 2) });
  };

  // Decrease font size
  const decreaseFontSize = () => {
    updateState(props._id, { fontSize: Math.max(8, s.fontSize - 2) });
  };

  return (
    <HStack>
      <HelpModal isOpen={helpIsOpen} onClose={helpOnClose} />
      <Badge colorScheme={badgeColorScheme} rounded="sm" size="lg">
        {badgeText}
      </Badge>
      {myKernels.length === 0 ? (
        <Button onClick={createDefaultKernel} _hover={{ opacity: 0.7 }} size="xs" mx="1" colorScheme="teal" isDisabled={!apiStatus}>
          Create Default Kernel <MdAdd />
        </Button>
      ) : (
        <Select
          // placeholder={selected?.is_private && user?._id !== selected.owner ? 'Private' : 'Select Kernel'}
          rounded="lg"
          size="sm"
          width="150px"
          ml={2}
          colorScheme="teal"
          icon={<MdArrowDropDown />}
          onChange={(e) => selectKernel(e as React.ChangeEvent<HTMLSelectElement>)}
          value={selected?.kernel_id}
          variant={'outline'}
          isDisabled={selected?.is_private && !access}
        >
          {
            //show my kernels
            myKernels
              .filter((el) => el.name === 'python3')
              .map((el) => (
                <option value={el.kernel_id} key={el.kernel_id}>
                  {el.alias} ({el.name === 'python3' ? 'Python' : el.name === 'r' ? 'R' : 'Julia'})
                </option>
              ))
          }
        </Select>
      )}

      <Tooltip placement="top-start" hasArrow={true} label={'Refresh Kernel List'} openDelay={400}>
        <Button onClick={refreshKernels} _hover={{ opacity: 0.7 }} size="xs" mx="1" colorScheme="teal">
          <MdRefresh />
        </Button>
      </Tooltip>

      <Tooltip placement="top-start" hasArrow={true} label={'Click for help'} openDelay={400}>
        <Button onClick={helpOnOpen} _hover={{ opacity: 0.7 }} size="xs" mx="1" colorScheme="teal">
          <MdHelp />
        </Button>
      </Tooltip>

      <ButtonGroup isAttached size="xs" colorScheme="teal">
        <Tooltip placement="top-start" hasArrow={true} label={'Decrease Font Size'} openDelay={400}>
          <Button isDisabled={s.fontSize <= 8} onClick={increaseFontSize} _hover={{ opacity: 0.7, transform: 'scaleY(1.3)' }}>
            <MdRemove />
          </Button>
        </Tooltip>
        <Tooltip placement="top-start" hasArrow={true} label={'Increase Font Size'} openDelay={400}>
          <Button isDisabled={s.fontSize > 42} onClick={decreaseFontSize} _hover={{ opacity: 0.7, transform: 'scaleY(1.3)' }}>
            <MdAdd />
          </Button>
        </Tooltip>
      </ButtonGroup>
      <ButtonGroup isAttached size="xs" colorScheme="teal">
        <Tooltip placement="top-start" hasArrow={true} label={'Download Code'} openDelay={400}>
          <Button onClick={downloadPy} _hover={{ opacity: 0.7 }}>
            <MdFileDownload />
          </Button>
        </Tooltip>
      </ButtonGroup>
    </HStack>
  );
}
