name: Docker Images DEV

on:
  push:
    branches: ["dev", "dev-langchain-deploy"]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-amd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.REGISTRY }}/sage-3/next:dev_amd64

      - name: Build and push image node_server
        uses: docker/build-push-action@v5
        with:
          file: deployment/node_server/Dockerfile
          context: "{{defaultContext}}:."
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/sage-3/next:dev_amd64
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push image seer
        uses: docker/build-push-action@v5
        with:
          file: deployment/seer/Dockerfile
          context: "{{defaultContext}}:."
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/sage-3/seer:dev_amd64
          # labels: ${{ steps.meta.outputs.labels }}

  build-and-push-arm:
    runs-on: [self-hosted, macOS, ARM64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: deployment/node_server/Dockerfile
            image: ghcr.io/sage-3/next
          - dockerfile: deployment/seer/Dockerfile
            image: ghcr.io/sage-3/agents
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: Build and push image node_server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
