name: Docker Images DEV

on:
  push:
    branches: ["dev"]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-amd:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: deployment/node_server/Dockerfile
            image: ghcr.io/sage-3/next
          - dockerfile: deployment/seer/Dockerfile
            image: ghcr.io/sage-3/seer
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Login To GitHub Container Registry
      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:."
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: dev_amd64
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-arm:
    runs-on: [self-hosted, macOS, ARM64]
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: deployment/node_server/Dockerfile
            image: ghcr.io/sage-3/next
          - dockerfile: deployment/seer/Dockerfile
            image: ghcr.io/sage-3/seer
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Login To GitHub Container Registry
      - name: Log in to the Container GHCR registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:."
          file: ${{ matrix.dockerfile }}
          platforms: linux/arm64
          push: true
          tags: dev_arm64
          labels: ${{ steps.meta.outputs.labels }}
