name: Tag release linux

on:
  push:
    branches:
      - dev
    tags:
      - "*"

env:
  SERVER: production

defaults:
  run:
    shell: bash
    working-directory: webstack/clients/electron

jobs:
  run:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        run: yarn install --frozen-lockfile --silent
      - name: Build
        run: npx electron-packager ./ --platform=linux --arch=x64 --icon=s3.icns --overwrite --appCopyright="SAGE3 Team"
      - name: Chmod
        run: chmod +x SAGE3-linux-x64/SAGE3
      - name: Readme
        run: cp README.lnx SAGE3-linux-x64/README.txt
        working-directory: webstack/clients/electron
      - name: Tar files
        run: tar -cvf SAGE3-linux-x64.tar SAGE3-linux-x64
      - uses: actions/upload-artifact@v4
        with:
          name: SAGE3-linux-client-ubuntu-24.04
          path: webstack/clients/electron/SAGE3-linux-x64


      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: webstack/clients/electron/SAGE3-linux-x64.tar
          name: SAGE3-linux-client-ubuntu-24.04.tar
